
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.text.SimpleDateFormat;




/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Bhawa
 */
public class ReturnBook extends javax.swing.JFrame {
       Connection con =Connect.Connection();
       PreparedStatement pst;
       ResultSet rs;
    /**
     * Creates new form ReturnBook
     */
    public ReturnBook() {
        initComponents();
         SimpleDateFormat  dat=new SimpleDateFormat("dd/MM/yyyy ");
         java.util.Date d=new java.util.Date();
         txtreturndate.setText(dat.format(d));
         txtbookid.setText("");
 txtbookid.setText("");
 txtbookname.setText("");
 txtstudentid.setText("");
 txtfacultyid.setText("");
 txtissuedate.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtbookid = new javax.swing.JTextField();
        txtreturndate = new javax.swing.JTextField();
        txtstudentid = new javax.swing.JTextField();
        txtfacultyid = new javax.swing.JTextField();
        txtbookname = new javax.swing.JTextField();
        txtissuedate = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnreturn = new javax.swing.JButton();
        txtsearch = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Wide Latin", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 255, 0));
        jLabel1.setText("RETURN BOOK");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 542, 68));

        jLabel2.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("BOOK ID:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 169, 34));

        jLabel3.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("STUDENT ID:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 177, -1));

        jLabel4.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("FACULTY ID:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("BOOK NAME:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, 185, -1));

        jLabel6.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ISSUE DATE:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 161, -1));

        jLabel7.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("RETURN DATE:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 620, 203, -1));

        txtbookid.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        getContentPane().add(txtbookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 110, 270, 34));

        txtreturndate.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        txtreturndate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtreturndateActionPerformed(evt);
            }
        });
        getContentPane().add(txtreturndate, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 630, 270, 34));

        txtstudentid.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        txtstudentid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstudentidActionPerformed(evt);
            }
        });
        getContentPane().add(txtstudentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 270, 34));

        txtfacultyid.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        getContentPane().add(txtfacultyid, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 270, 34));

        txtbookname.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        getContentPane().add(txtbookname, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 270, 34));

        txtissuedate.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        getContentPane().add(txtissuedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 530, 270, 34));

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bhawa\\Downloads\\Screenshot 2025-05-24 001327.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 27, 26));

        btnreturn.setBackground(new java.awt.Color(0, 102, 102));
        btnreturn.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        btnreturn.setText("RETURN");
        btnreturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnreturnActionPerformed(evt);
            }
        });
        getContentPane().add(btnreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 710, -1, -1));

        txtsearch.setBackground(new java.awt.Color(0, 153, 153));
        txtsearch.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtsearch.setText("SEARCH");
        txtsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsearchActionPerformed(evt);
            }
        });
        getContentPane().add(txtsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(903, 110, -1, 30));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bhawa\\Downloads\\Screenshot 2025-05-24 020519.png")); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtreturndateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtreturndateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtreturndateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtstudentidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstudentidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstudentidActionPerformed

    private void txtsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsearchActionPerformed
                 
        if (txtbookid.getText().equals("") ){
        JOptionPane.showMessageDialog(this,"Please enter book id and search it");// TODO add your handling code here:
        txtbookid.requestFocus();
    }                                     
    else{
        try {
            pst=con.prepareStatement("SELECT * from book where id=?");
            /*if (txtbookid.getText().equals("")){
        JOptionPane.showMessageDialog(this,"Please enter book id and search it");// TODO add your handling code here:
        txtbookid.requestFocus();*/
            pst.setString(1,txtbookid.getText());
            rs=pst.executeQuery();
            
            
            // txtissuedate.setText(rs.getString(7));
            
            if(rs.next()){
                txtbookname.setText(rs.getString(2));
                txtstudentid.setText(rs.getString(9));
                txtfacultyid.setText(rs.getString(10));
                txtissuedate.setText(rs.getString(7));

                

        
             //   txtduedate.setText(rs.getString(8));
             
                }
                            
             
            else if (txtissuedate.getText().equals(null)){
                
                
        JOptionPane.showMessageDialog(this,"Not Available!!!");// TODO add your handling code here:
        txtbookid.requestFocus();
        
    }  else if (txtissuedate.getText().equals("")){
           
           
        JOptionPane.showMessageDialog(this,"Not Available!!!");// TODO add your handling code here:
        txtbookid.requestFocus();
    } 
    
                
                
                
                
                
                
                
                
                
                
                
                else {
                JOptionPane.showMessageDialog(this,"Not Issued!! Try again!!!");
                pst=con.prepareStatement("SELECT * FROM studentregistration where id=?");
            pst.setString(1, txtbookid.getText());
            rs=pst.executeQuery();
           
            
           // JOptionPane.showMessageDialog(this,"Not A!! Try again!!!");
            
            
            }
}catch (SQLException ex) {
            Logger.getLogger(ReturnBook.class.getName()).log(Level.SEVERE, null, ex);
        }
        
            
            
            
}

         /* if (txtissuedate.getText().equals("null")){
        JOptionPane.showMessageDialog(this,"Not Issued Yet!!!");// TODO add your handling code here:
        txtbookid.requestFocus();
        
    }   else if (txtissuedate.getText().equals("")){
           
           
        JOptionPane.showMessageDialog(this,"Not Issued Yet!!!");// TODO add your handling code here:
        txtbookid.requestFocus();
    }  */ 
             
             
             

         
        
        
        
        
             /* try {
                 
                  pst=con.prepareStatement(" select * from book where id=?");  
                  pst.setString(1, txtstudentid.getText());
                  rs=pst.executeQuery();
                  
                  if(rs.next()){
                           
                               txtbookname.setText(rs.getString("name"));
                    txtbookid.setText(rs.getString("id"));
                    txtissuedate.setText(rs.getString("issue"));
                    txtreturndate.setText(rs.getString("due"));



                       
                      //txtbookname.setText(rs.getString(2));
                      //txtfacultyid.setText(rs.getString(2));
                      //txtfacultyid.setText(rs.getString(2));
                      
                      //txtreturndate.setText(rs.getString(4));
                     // txtissuedate.setText(rs.getString(5));
                  }else {
                  JOptionPane.showMessageDialog(this,"Please enter valid id");
                   pst=con.prepareStatement("SELECT * FROM library.student where id=?");
            pst.setString(1, txtbookid.getText());
            rs=pst.executeQuery();
            if(rs.next()){
                    txtbookname.setText(rs.getString("name"));
            
                    }
                    catch (SQLException ex) {
                  Logger.getLogger(ReturnBook.class.getName()).log(Level.SEVERE, null, ex);
                   }
          
    }//GEN-LAST:event_txtsearchActionPerformed
              */
    
    }
    private void btnreturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnreturnActionPerformed
        // TODO add your handling code here:
        if(txtbookid.getText().equals("")){
              JOptionPane.showMessageDialog(this,"Please enter book id and search.");
              txtbookid.requestFocus();
        }
        
        
        
        
        else if(txtissuedate.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Not Issued! Try with different Book id.");
              txtbookid.requestFocus();
            
        }
        
        
        else{
           
            
                try {
 Connection con =Connect.Connection();
                    PreparedStatement pst;
                    pst=con.prepareStatement("UPDATE book set status='Available',issuedate='',duedate='',studentid= ?,facultyid=? where id=?");
                
                    //pst.setString(1,"Available");
                    pst.setString(3, txtbookid.getText());
                     pst.setString(1,null);
                      pst.setString(2,null);
                    
                    pst.executeUpdate();
                    JOptionPane.showMessageDialog(this,"Book Returned");
                    
                    txtbookid.setText("");
                     txtbookname.setText("");
                    txtstudentid.setText("");
                    txtfacultyid.setText("");
                    txtissuedate.setText("");
                    //txtreturndate.setText("");
                    
                } catch (SQLException ex) {
                    Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
                }
            
            
        
        
    }//GEN-LAST:event_btnreturnActionPerformed
         
}                            
                             
                  
             
                  
                
                          
                       
                  
             
         
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnreturn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtbookid;
    private javax.swing.JTextField txtbookname;
    private javax.swing.JTextField txtfacultyid;
    private javax.swing.JTextField txtissuedate;
    private javax.swing.JTextField txtreturndate;
    private javax.swing.JButton txtsearch;
    private javax.swing.JTextField txtstudentid;
    // End of variables declaration//GEN-END:variables

}




